test_configuration:
  target: ProtoDesignSystemTests
  test_target_path: ${PROJECT_DIR}/ProtoDesignSystemTests
  test_file_path: ProtoDesignSystemTests/PreviewTests.generated.swift
  simulator_device: "iPhone15,2"
  required_os: 16
  preview_default_enabled: true
  use_grouped_snapshots: true
  sources:
    - ${PROJECT_DIR}/ProtoDesignSystem/Sources/
  snapshot_devices:
    - iPhone 14
    - iPad
  imports:
    - SwiftUI
  testable_imports:
    - ProtoDesignSystem
